name: Link checker
on:
  pull_request:
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
