name: Link checker
on:
  pull_request:
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
